### ISSUE TITLE
Location of debug log shown in UI is not correct 

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/vendor#131]
With #102 the location of log file changed, there is a [private method](https://github.com/trustedlogin/vendor/pull/102/files#diff-fea009d1dfdc87fe048f741c4bd7f7ce9e5b2e68ca15bc213dfa8196d51465d5R110) for dir name.

In UI location is hardcoded. [`<code>wp-content/uploads/trustedlogin-logs</code>` is displayed](https://github.com/trustedlogin/vendor/blob/develop/src/components/Sections.js#L226)

**Comment by zackkatz** [comment]
@Shelob9 This was resolved in 30c21da

**Comment by Shelob9** [comment]
@zackkatz That is unrelated. I am refering to where it is displayed in UI https://github.com/trustedlogin/vendor/blob/develop/src/components/Sections.js#L226

**Comment by Shelob9** [comment]
![Screenshot 2023-02-28 121931](https://user-images.githubusercontent.com/1994311/221928811-ada1e6d3-b772-4e8f-9597-a4e0e163b82b.jpg)
