### ISSUE TITLE
Make audit log do something

### ISSUE THREAD

**Issue by Shelob9** [trustedlogin/vendor#5]

**Comment by zackkatz** [comment]
This is a priority; when something doesn't work, having a log is vital.

**Comment by Shelob9** [comment]
Right now, there is a logging trait, which is ued a lot, that logs to file. https://github.com/trustedlogin/vendor/blob/main/php/Traits/Logger.php#L13-L35

There is also an AuditLog class, that's used in a few places, it does nothing. Probably should log to app.

https://github.com/trustedlogin/vendor/blob/main/php/AuditLog.php

**Comment by Shelob9** [comment]
- [ ] Change log location to upload, with hash to obsfucate where it is stored.
- [ ] Make audit log, log to elastic search
- [ ] Check that logger isn't getting things that should be in audit log.

**Comment by Shelob9** [comment]
@zackkatz Currently the audit log is only called in one place, and it's code that never runs. The point of the audit log is to know when a login request was made, right? We have that data logged server-side. I think we should remove AuditLog class from plugin, and then close issue. I opened #83 to track changing location of debug log.

**Comment by Shelob9** [comment]
#96
